services:
  web:
    build: ..
    container_name: django_app
    command: sh -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./static:/app/static  # Store static files persistently
      - ./media:/app/media    # Store media files persistently
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev

  db:
    image: postgres:17.4
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.dev

  pgadmin:  # 🆕 Add pgAdmin Service
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Change this
      PGADMIN_DEFAULT_PASSWORD: admin123  # Change this
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  static_volume:
  media_volume:
  pgadmin_data:  
