apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NEXT_PUBLIC_BACKEND_URL: "http://django:8000"
  NEXT_PUBLIC_SITE_URL: "a044a0d5c55b54768bdda788b5e9965d-1372228647.us-east-1.elb.amazonaws.com:3000"