apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NEXT_PUBLIC_BACKEND_URL: "http://django:8000"
  NEXT_PUBLIC_SITE_URL: "http://ab63998ace4b24dc28a1a869d759c3c2-46855222.us-east-1.elb.amazonaws.com:3000"