services:
  web:
    build: ../backend
    container_name: django_app
    command: sh -c "python manage.py collectstatic --noinput &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend:/app
      - ../backend/static:/app/static
      - ../backend/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_ALLOWED_HOSTS: "54.242.180.95 web localhost"
    env_file:
      - ./../backend/.env.dev

  db:
    image: postgres:17.4
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

#  front:
#    build: ../frontend
#    container_name: nextjs_app
#    ports:
#      - "3000:3000"
#    depends_on:
#      - web
#    environment:
#      NEXT_PUBLIC_BACKEND_URL: http://web:8000
#    env_file:
#      - ./../frontend/.env.docker

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"  # expose redis
    volumes:
      - redis_data:/data #persist data

volumes:
  postgres_data:
  static_volume:
  media_volume:
  pgadmin_data:
  redis_data:
