# Generated by Django 4.2.19 on 2025-04-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="user",
            new_name="receiver",
        ),
    ]
