# Generated by Django 4.2.19 on 2025-04-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0003_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="recipient",
            new_name="receiver",
        ),
    ]
