# Generated by Django 4.2.19 on 2025-05-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0004_rename_recipient_message_receiver"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-sent_at"]},
        ),
    ]
