# Generated by Django 4.2.19 on 2025-04-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_tag_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="file",
        ),
    ]
