# Generated by Django 4.2.19 on 2025-05-03 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_alter_category_options_topicviewlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicviewlog",
            name="viewed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
