apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_ALLOWED_HOSTS: "52.70.58.244 web localhost"
  DEBUG: 'True'
  SECRET_KEY: 'your_secret_key_here'
  POSTGRES_DB: 'postgres'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'
  POSTGRES_HOST: 'postgres'
  POSTGRES_PORT: '5432'